artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sandeepmande29/Data/raw/main/Thyroid_Detection.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Thyroid_Detection.csv
  STATUS_FILE: artifacts/data_validation/status.txt




data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Thyroid_Detection.csv
  encoder_name: preprocessed.joblib



model_trainer:
  root_dir: artifacts/model_trainer
  train_x_data_path: artifacts/data_transformation/x_train.csv
  test_x_data_path: artifacts/data_transformation/x_test.csv
  train_y_data_path: artifacts/data_transformation/y_train.csv
  test_y_data_path: artifacts/data_transformation/y_test.csv
  model_name: model.joblib